export const MENU_MUSIC_SELECT = 'MENU_MUSIC_SELECT';
export const MENU_DJ_MODE = 'MENU_DJ_MODE';
export const MENU_OPTIONS = 'MENU_OPTIONS';
export const DISC_LABEL = 'DISC_LABEL';
export const MUSIC_SELECT_PLAY_BUTTON = 'MUSIC_SELECT_PLAY_BUTTON';
export const MUSIC_SELECT_BACK_BUTTON = 'MUSIC_SELECT_BACK_BUTTON';
